tag_checker:
  stage: build
  script:
    - python3 tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - mvn -B clean test -Dprism.verbose=true -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dheadless.geometry=1920x1080-32

recent-artifacts:
  stage: deploy
  script:
    - mvn -B clean package -DskipTests
    - mvn -B package
  artifacts:
    paths:
      - client/target/*.jar
      - server/target/*.jar
      - target/site/jacoco/*
    expire_in: 1 week
  except:
    - tags

release-artifacts:
  stage: deploy
  script:
    - mvn -B clean install -DskipTests
    - mvn -B site sonar:sonar package
  artifacts:
    paths:
    - target/*.jar
    - client/target/*.jar
    - client/target/site/jacoco/*
    - server/target/*.jar
    - server/target/site/jacoco/*
    - commons/target/site/jacoco/*
  only:
    - tags
    - dev@seng302-2018/team-200
