tag_checker:
  stage: build
  script:
    - python3 tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - mvn -B clean test

recent-artifacts:
  stage: deploy
  script:
    - mvn -B clean package -DskipTests
    - mvn -B package
  artifacts:
    paths:
      - client/target/*.jar
      - server/target/*.jar
      - target/site/jacoco/*
    expire_in: 1 week
  except:
    - tags
    - dev@seng302-2018/team-200
    - release@seng302-2018/team-200

server-build-image:
  stage: build
  script:
    - docker-compose build
  only:
    - server-deployment@seng302-2018/team-200
    - master@seng302-2018/team-200

server-deployment:
  stage: deploy
  script:
    - docker stop team300_app_1
    - docker stop testing
    - docker container prune -f
    - docker-compose up -d
    - docker run -d -p 6970:6969 --name testing team200_app /srv/java/jvm/bin/java -jar target/server-1.0-SNAPSHOT.jar -t
  only:
    - server-deployment@seng302-2018/team-300
    - master@seng302-2018/team-300


release-artifacts:
  stage: deploy
  script:
    - mvn -B clean install -DskipTests
    - mvn -B site sonar:sonar package
  artifacts:
    paths:
    - target/*.jar
    - client/target/*.jar
    - client/target/site/jacoco/*
    - server/target/*.jar
    - server/target/site/jacoco/*
    - commons/target/site/jacoco/*
  only:
    - tags
    - dev@seng302-2018/team-200
    - release@seng302-2018/team-200
